// services/bff/src/admin_config_summary.ts
//
// T6 M13.9 — Admin config printable summary export.
//
// M13.1 ships the registry, M13.2 the audit-trail, M13.5 the diff,
// M13.7 selective clone, M13.8 bulk-reset. What ops have asked
// for next: a printable plain-text view of the WHOLE tenant
// config — every key, its effective value, where the value came
// from (tenant override vs platform default) — suitable for
// attaching to an audit pack via browser print-to-PDF.
//
// Mirrors M15.4 (audit evidence) + M7.6 (model performance)
// style: fixed-width monospace, no external dependencies,
// per-category sections.

import {
  type ConfigCategory,
  type ConfigEntry,
  type ConfigValue,
  listCategories,
} from './admin_config';

const RULE = '─'.repeat(72);
const SUB_RULE = '·'.repeat(72);

function pad(s: string, n: number, ch = ' '): string {
  return s.length >= n ? s : s + ch.repeat(n - s.length);
}

function fmtValue(v: ConfigValue): string {
  if (v === null || v === undefined) return '—';
  if (typeof v === 'string') return v.length === 0 ? '""' : v;
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  return JSON.stringify(v);
}

export interface ConfigSummaryRenderContext {
  /** ISO timestamp the report was generated. */
  generated_at: string;
  /** X-APEX-USER who pulled the report. */
  generated_by: string;
}

/**
 * Pure renderer — produces plain-text suitable for `text/plain`
 * + browser print-to-PDF. Mirrors `renderEvidenceSummary` style.
 */
export function renderConfigSummary(
  tenant_id: string,
  entries: readonly ConfigEntry[],
  ctx: ConfigSummaryRenderContext,
): string {
  const lines: string[] = [];

  const override_count = entries.filter((e) => !e.is_default).length;
  const default_count = entries.length - override_count;

  // ── Header ───────────────────────────────────────────────────────
  lines.push(RULE);
  lines.push('  ADMIN CONFIG — TENANT SUMMARY');
  lines.push(RULE);
  lines.push('');
  lines.push(`  Tenant            : ${tenant_id}`);
  lines.push(`  Generated at      : ${ctx.generated_at}`);
  lines.push(`  Generated by      : ${ctx.generated_by}`);
  lines.push(`  Total keys        : ${entries.length}`);
  lines.push(`  Tenant overrides  : ${override_count}`);
  lines.push(`  Platform defaults : ${default_count}`);
  lines.push('');

  // ── Per-category sections ────────────────────────────────────────
  const byCategory = new Map<ConfigCategory, ConfigEntry[]>();
  for (const e of entries) {
    let bucket = byCategory.get(e.category);
    if (!bucket) {
      bucket = [];
      byCategory.set(e.category, bucket);
    }
    bucket.push(e);
  }

  for (const category of listCategories()) {
    const bucket = byCategory.get(category);
    if (!bucket || bucket.length === 0) continue;
    bucket.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
    lines.push(SUB_RULE);
    lines.push(`  ${category.toUpperCase()}  (${bucket.length} key${bucket.length === 1 ? '' : 's'})`);
    lines.push(SUB_RULE);
    for (const e of bucket) {
      const sourceTag = e.is_default ? '(default)' : '(override)';
      lines.push(`  ${pad(e.key, 40)}  ${pad(e.type, 8)}  ${sourceTag}`);
      lines.push(`    value : ${fmtValue(e.value)}`);
      if (!e.is_default && e.updated_at) {
        lines.push(`    set   : ${e.updated_at}  by ${e.updated_by ?? '(unknown)'}`);
      }
    }
    lines.push('');
  }

  // ── Footer ───────────────────────────────────────────────────────
  lines.push(RULE);
  lines.push('  END OF SUMMARY');
  lines.push(RULE);
  lines.push('');

  return lines.join('\n');
}
