// services/bff/src/audit_evidence_summary.ts
//
// T6 M15.4 — Evidence package summary export.
//
// M15.3 ships the frozen evidence package — JSON envelope with
// chain-verification metadata and the full event list. Auditors
// who want to attach a snapshot to a regulator filing need a
// PRINTABLE form. M15.4 ships a pure-function plain-text
// summary that the SPA can render to PDF via the browser's
// built-in print pipeline (no Node-side PDF dep, keeps the
// prototype zero-binary).
//
// Output is a fixed-width plain-text document — Markdown-ish but
// no table libraries, no escapes. Looks crisp in monospace.

import {
  type AuditEvent,
  type AuditAction,
  type AuditResourceType,
  type AuditSeverity,
  type AuditOutcome,
} from './audit_trail';
import { type EvidencePackage } from './audit_evidence';

const RULE = '─'.repeat(72);
const SUB_RULE = '·'.repeat(72);

function pad(s: string, n: number, ch = ' '): string {
  return s.length >= n ? s : s + ch.repeat(n - s.length);
}

function group<T, K extends string>(
  items: readonly T[],
  key: (t: T) => K,
): Record<K, number> {
  const out = {} as Record<K, number>;
  for (const it of items) {
    const k = key(it);
    out[k] = (out[k] ?? 0) + 1;
  }
  return out;
}

function fmtFilters(filters: EvidencePackage['filters']): string[] {
  const lines: string[] = [];
  const keys: Array<keyof EvidencePackage['filters']> = [
    'since',
    'until',
    'actor_username',
    'action',
    'resource_type',
    'resource_id',
    'outcome',
    'severity',
  ];
  for (const k of keys) {
    const v = filters[k];
    if (v !== undefined && v !== null) {
      lines.push(`  ${pad(`${k}:`, 18)} ${String(v)}`);
    }
  }
  if (lines.length === 0) lines.push('  (no filters — full tenant trail captured)');
  return lines;
}

function fmtEvent(e: AuditEvent, idx: number, total: number): string {
  const idxStr = pad(`#${idx + 1}/${total}`, 8);
  const ts = e.ts;
  const actor = pad(e.actor_username, 24);
  const action = pad(e.action, 26);
  const outcome = pad(e.outcome, 8);
  const sev = pad(e.severity, 8);
  return `  ${idxStr} ${ts}  ${actor}  ${action}  ${outcome}  ${sev}  ${e.resource_type}/${e.resource_id}`;
}

/**
 * Pure-function summary renderer. Produces plain-text suitable
 * for `text/plain` response and direct print-to-PDF in the browser.
 */
export function renderEvidenceSummary(pkg: EvidencePackage): string {
  const lines: string[] = [];

  // Header
  lines.push(RULE);
  lines.push('  EVIDENCE PACKAGE — SUMMARY');
  lines.push(RULE);
  lines.push('');
  lines.push(`  Package ID    : ${pkg.package_id}`);
  lines.push(`  Tenant        : ${pkg.tenant_id}`);
  lines.push(`  Generated at  : ${pkg.generated_at}`);
  lines.push(`  Generated by  : ${pkg.generated_by}`);
  lines.push(`  Event count   : ${pkg.event_count}`);
  lines.push(`  Size (bytes)  : ${pkg.size_bytes}`);
  lines.push('');

  // Integrity
  lines.push(SUB_RULE);
  lines.push('  INTEGRITY');
  lines.push(SUB_RULE);
  const verifiedTag = pkg.integrity.chain_verified ? 'PASS' : 'FAIL';
  lines.push(`  Chain verified: ${verifiedTag}`);
  lines.push(`  Chain anchor  : ${pkg.integrity.chain_last_hash}`);
  if (pkg.integrity.first_event_hash) {
    lines.push(`  First event   : ${pkg.integrity.first_event_hash}`);
  }
  if (pkg.integrity.last_event_hash) {
    lines.push(`  Last event    : ${pkg.integrity.last_event_hash}`);
  }
  if (!pkg.integrity.chain_verified && pkg.integrity.broken_at) {
    const b = pkg.integrity.broken_at;
    lines.push(
      `  Broken at     : index=${b.index} event=${b.event_id} reason=${b.reason}`,
    );
  }
  lines.push('');

  // Filters
  lines.push(SUB_RULE);
  lines.push('  FILTERS APPLIED');
  lines.push(SUB_RULE);
  for (const f of fmtFilters(pkg.filters)) lines.push(f);
  lines.push('');

  // Aggregate counts
  lines.push(SUB_RULE);
  lines.push('  COUNTS BY ACTION / RESOURCE / OUTCOME / SEVERITY');
  lines.push(SUB_RULE);
  const byAction = group<AuditEvent, AuditAction>(pkg.events, (e) => e.action);
  const byResource = group<AuditEvent, AuditResourceType>(pkg.events, (e) => e.resource_type);
  const byOutcome = group<AuditEvent, AuditOutcome>(pkg.events, (e) => e.outcome);
  const bySeverity = group<AuditEvent, AuditSeverity>(pkg.events, (e) => e.severity);
  lines.push('  By action:');
  for (const [k, n] of Object.entries(byAction).sort((a, b) => b[1] - a[1])) {
    lines.push(`    ${pad(k, 32)} ${n}`);
  }
  lines.push('  By resource_type:');
  for (const [k, n] of Object.entries(byResource).sort((a, b) => b[1] - a[1])) {
    lines.push(`    ${pad(k, 32)} ${n}`);
  }
  lines.push('  By outcome:');
  for (const [k, n] of Object.entries(byOutcome).sort((a, b) => b[1] - a[1])) {
    lines.push(`    ${pad(k, 32)} ${n}`);
  }
  lines.push('  By severity:');
  for (const [k, n] of Object.entries(bySeverity).sort((a, b) => b[1] - a[1])) {
    lines.push(`    ${pad(k, 32)} ${n}`);
  }
  lines.push('');

  // Event list (time order)
  lines.push(SUB_RULE);
  lines.push('  EVENTS (oldest first)');
  lines.push(SUB_RULE);
  if (pkg.events.length === 0) {
    lines.push('  (no events captured)');
  } else {
    const sorted = [...pkg.events].sort((a, b) =>
      a.ts < b.ts ? -1 : a.ts > b.ts ? 1 : 0,
    );
    for (let i = 0; i < sorted.length; i++) {
      lines.push(fmtEvent(sorted[i]!, i, sorted.length));
    }
  }
  lines.push('');
  lines.push(RULE);
  lines.push('  END OF SUMMARY');
  lines.push(RULE);
  lines.push('');

  return lines.join('\n');
}
