// services/bff/src/model_performance_summary.ts
//
// T6 M7.6 — Model performance summary printable text export.
//
// M7.5 ships the per-(tenant, model) performance ledger plus the
// `summarizePerformance()` aggregator. MLOps reviewers + risk
// committees need a printable form they can attach to a model card
// or a regulatory filing. M7.6 ships a pure-function plain-text
// renderer mirroring the M15.4 evidence-summary style: fixed-width
// monospace, no external dependencies, ready for the browser's
// print-to-PDF pipeline.

import {
  PERFORMANCE_METRICS,
  type ModelPerformanceSummary,
  type PerformanceMetric,
} from './model_performance';

const RULE = '─'.repeat(72);
const SUB_RULE = '·'.repeat(72);

function pad(s: string, n: number, ch = ' '): string {
  return s.length >= n ? s : s + ch.repeat(n - s.length);
}

function fmtNum(v: number | null | undefined, digits = 4): string {
  if (v === null || v === undefined || !Number.isFinite(v)) return '—';
  // Trim trailing zeros after fixed-point for readability.
  const s = v.toFixed(digits);
  return s.replace(/\.?0+$/, '') || '0';
}

/** Optional rendering context — passed through to the header. */
export interface PerformanceSummaryRenderContext {
  /** ISO timestamp this report was generated. */
  generated_at: string;
  /** Caller (X-APEX-USER) for the audit trail header line. */
  generated_by: string;
  /** Optional filter window the summary covered. */
  range?: { since?: string; until?: string };
}

/**
 * Pure-function summary renderer. Produces plain-text suitable for
 * a `text/plain` response and direct print-to-PDF in the browser.
 * Mirrors `renderEvidenceSummary` in style + posture.
 */
export function renderPerformanceSummary(
  summary: ModelPerformanceSummary,
  ctx: PerformanceSummaryRenderContext,
): string {
  const lines: string[] = [];

  // ── Header ───────────────────────────────────────────────────────
  lines.push(RULE);
  lines.push('  MODEL PERFORMANCE — SUMMARY');
  lines.push(RULE);
  lines.push('');
  lines.push(`  Tenant         : ${summary.tenant_id}`);
  lines.push(`  Model ID       : ${summary.model_id}`);
  lines.push(`  Generated at   : ${ctx.generated_at}`);
  lines.push(`  Generated by   : ${ctx.generated_by}`);
  lines.push(`  Entry count    : ${summary.sample_size}`);
  if (ctx.range && (ctx.range.since || ctx.range.until)) {
    const since = ctx.range.since ?? '—';
    const until = ctx.range.until ?? '—';
    lines.push(`  Window         : ${since} → ${until}`);
  } else {
    lines.push(`  Window         : (full ledger — no since/until filter)`);
  }
  lines.push('');

  // ── Per-metric blocks ────────────────────────────────────────────
  lines.push(SUB_RULE);
  lines.push('  METRICS');
  lines.push(SUB_RULE);
  const presentMetrics: PerformanceMetric[] = [];
  const absentMetrics: PerformanceMetric[] = [];
  for (const m of PERFORMANCE_METRICS) {
    if (summary.metrics[m] !== null) presentMetrics.push(m);
    else absentMetrics.push(m);
  }

  if (presentMetrics.length === 0) {
    lines.push('  (no observations on any metric in this window)');
  } else {
    for (const m of presentMetrics) {
      const row = summary.metrics[m]!;
      lines.push('');
      lines.push(`  ${pad(m, 18)} (n=${row.sample_count})`);
      lines.push(`    latest          ${fmtNum(row.latest_value)}  @ ${row.latest_at}`);
      lines.push(`    mean            ${fmtNum(row.mean)}`);
      lines.push(`    min / p50 / p95 / max  ${fmtNum(row.min)}  /  ${fmtNum(row.p50)}  /  ${fmtNum(row.p95)}  /  ${fmtNum(row.max)}`);
    }
    if (absentMetrics.length > 0) {
      lines.push('');
      lines.push(`  Not observed: ${absentMetrics.join(', ')}`);
    }
  }
  lines.push('');

  // ── Footer ───────────────────────────────────────────────────────
  lines.push(RULE);
  lines.push('  END OF SUMMARY');
  lines.push(RULE);
  lines.push('');

  return lines.join('\n');
}
