// web/src/lib/export/generators/docx.ts — professional Word document.
// Sections per spec: header/meta, Executive Summary, Detailed Findings,
// Recommendations, Approvals, Comments.
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, AlignmentType,
} from 'docx';
import type { ReportData, ExportConfig, ReportTable } from '../types';

function headingPara(text: string): Paragraph {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 } });
}
function kvTable(rows: { label: string; value: string }[]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: rows.map((r) => new TableRow({
      children: [
        new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: r.label, bold: true })] })] }),
        new TableCell({ children: [new Paragraph(r.value)] }),
      ],
    })),
  });
}
function dataTable(t: ReportTable): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: t.columns.map((c) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: c, bold: true })] })] })) }),
      ...t.rows.slice(0, 200).map((row) => new TableRow({
        children: row.map((cell) => new TableCell({ children: [new Paragraph(String(cell ?? ''))] })),
      })),
    ],
  });
}

export async function buildReportDocxBlob(data: ReportData, config: ExportConfig): Promise<Blob> {
  const m = data.meta;
  const inc = config.include;
  const s = data.sections;
  const children: (Paragraph | Table)[] = [];

  // Header / meta block.
  children.push(new Paragraph({ children: [new TextRun({ text: 'ZorEWS', bold: true, size: 32 })], alignment: AlignmentType.LEFT }));
  children.push(new Paragraph({ children: [new TextRun({ text: 'Early Warning System', italics: true, color: '666666' })] }));
  children.push(new Paragraph({ text: data.title, heading: HeadingLevel.HEADING_1, spacing: { before: 120, after: 120 } }));
  children.push(kvTable([
    { label: 'Tenant', value: m.tenant_id },
    { label: 'Generated By', value: `${m.generated_by} (${m.role})` },
    { label: 'Generated', value: m.generated_at },
    { label: 'Report ID', value: m.report_id },
  ]));

  // Executive Summary.
  if (inc.summary && (s.summary?.length || s.kpis?.length)) {
    children.push(headingPara('Executive Summary'));
    if (s.summary?.length) children.push(kvTable(s.summary));
    if (inc.kpis && s.kpis?.length) children.push(kvTable(s.kpis.map((k) => ({ label: k.label, value: k.value + (k.delta ? ` (${k.delta})` : '') }))));
  }

  // AI Insight (narrative).
  if (inc.ai_insights && s.ai_insights?.narrative) {
    children.push(headingPara('AI Insight'));
    children.push(new Paragraph(s.ai_insights.narrative));
  }

  // Detailed Findings (tables).
  if ((s.tables ?? []).length) {
    children.push(headingPara('Detailed Findings'));
    for (const t of s.tables ?? []) {
      children.push(new Paragraph({ children: [new TextRun({ text: t.name, bold: true })], spacing: { before: 120, after: 60 } }));
      children.push(dataTable(t));
    }
  }

  // Recommendations.
  if (inc.recommendations && s.recommendations?.length) {
    children.push(headingPara('Recommendations'));
    s.recommendations.forEach((r) => children.push(new Paragraph({ text: r, bullet: { level: 0 } })));
  }

  // Approvals + Comments (blank professional placeholders).
  children.push(headingPara('Approvals'));
  children.push(kvTable([{ label: 'Reviewed By', value: '' }, { label: 'Approved By', value: '' }, { label: 'Date', value: '' }]));
  children.push(headingPara('Comments'));
  children.push(new Paragraph(''));

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBlob(doc);
}
