// web/src/lib/export/generators/pdf.ts — enterprise-styled, section-driven PDF.
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ReportData, ExportConfig } from '../types';

const BRAND: [number, number, number] = [37, 99, 235];
const MARGIN = 40;

function cursorAfter(doc: jsPDF, fallback: number): number {
  // @ts-expect-error — autoTable mutates the doc with lastAutoTable.
  return (doc.lastAutoTable?.finalY ?? fallback) + 20;
}

export function buildReportPdf(data: ReportData, config: ExportConfig): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });

  // Header block.
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text('ZorEWS', MARGIN, MARGIN);
  doc.setFontSize(10);
  doc.setTextColor(110);
  doc.text('Early Warning System', MARGIN, MARGIN + 15);
  doc.setFontSize(9);
  const m = data.meta;
  doc.text(`Tenant: ${m.tenant_id}`, MARGIN, MARGIN + 32);
  doc.text(`Generated By: ${m.generated_by} (${m.role})`, MARGIN, MARGIN + 44);
  doc.text(`Generated: ${m.generated_at}`, MARGIN, MARGIN + 56);
  doc.text(`Report ID: ${m.report_id}`, MARGIN, MARGIN + 68);
  doc.setTextColor(0);
  doc.setFontSize(13);
  doc.text(data.title, MARGIN, MARGIN + 92);
  let y = MARGIN + 110;

  const inc = config.include;
  const s = data.sections;

  if (inc.summary && s.summary?.length) {
    autoTable(doc, {
      startY: y, head: [['Summary', 'Value']],
      body: s.summary.map((r) => [r.label, r.value]),
      theme: 'grid', styles: { fontSize: 8 }, headStyles: { fillColor: BRAND },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = cursorAfter(doc, y);
  }
  if (inc.kpis && s.kpis?.length) {
    autoTable(doc, {
      startY: y, head: [['KPI', 'Value', 'Δ']],
      body: s.kpis.map((k) => [k.label, k.value, k.delta ?? '—']),
      theme: 'grid', styles: { fontSize: 8 }, headStyles: { fillColor: BRAND },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = cursorAfter(doc, y);
  }
  for (const t of s.tables ?? []) {
    autoTable(doc, {
      startY: y, head: [t.columns], body: t.rows.slice(0, 200).map((r) => r.map((c) => String(c ?? '—'))),
      theme: 'striped', styles: { fontSize: 7, cellPadding: 3 }, headStyles: { fillColor: BRAND, fontSize: 8 },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = cursorAfter(doc, y);
  }
  if (inc.recommendations && s.recommendations?.length) {
    doc.setFontSize(10); doc.text('Recommendations', MARGIN, y); y += 14;
    doc.setFontSize(8);
    s.recommendations.forEach((r) => { doc.text(`• ${r}`, MARGIN, y); y += 12; });
  }
  if (inc.ai_insights && s.ai_insights?.narrative) {
    doc.setFontSize(10); doc.text('AI Insight', MARGIN, y); y += 14;
    doc.setFontSize(8);
    doc.splitTextToSize(s.ai_insights.narrative, 515).forEach((line: string) => { doc.text(line, MARGIN, y); y += 11; });
  }

  // Footer + page numbers.
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    const h = doc.internal.pageSize.getHeight();
    const w = doc.internal.pageSize.getWidth();
    doc.setFontSize(7); doc.setTextColor(140);
    doc.text('Confidential — Generated from ZorEWS', MARGIN, h - 20);
    doc.text(`Page ${p} of ${pages}`, w - MARGIN - 60, h - 20);
    doc.setTextColor(0);
  }
  return doc;
}

export function reportPdfBlob(data: ReportData, config: ExportConfig): Blob {
  return buildReportPdf(data, config).output('blob');
}
