// web/src/lib/export/generators/xlsx.ts — multi-sheet workbook.
import writeXlsxFile, { type Sheet } from 'write-excel-file/browser';
import type { ReportData, ExportConfig } from '../types';

interface Cell {
  value?: string | number | null;
  fontWeight?: 'bold';
  backgroundColor?: string;
  color?: string;
  type?: typeof String | typeof Number;
}
const HEAD = (label: string): Cell => ({ value: label, fontWeight: 'bold', backgroundColor: '#2563EB', color: '#FFFFFF' });
const cell = (v: string | number): Cell =>
  typeof v === 'number' && Number.isFinite(v) ? { type: Number, value: v } : { type: String, value: String(v ?? '') };

export async function buildReportXlsxBlob(data: ReportData, config: ExportConfig): Promise<Blob> {
  const s = data.sections;
  const m = data.meta;

  const summary: Cell[][] = [
    [HEAD('Field'), HEAD('Value')],
    [{ value: 'Report' }, { value: data.title }],
    [{ value: 'Tenant' }, { value: m.tenant_id }],
    [{ value: 'Generated By' }, { value: `${m.generated_by} (${m.role})` }],
    [{ value: 'Generated At' }, { value: m.generated_at }],
    [{ value: 'Report ID' }, { value: m.report_id }],
    ...(s.summary ?? []).map((r) => [{ value: r.label }, { value: r.value }]),
    ...(s.kpis ?? []).map((k) => [{ value: `KPI: ${k.label}` }, { value: k.value }]),
  ];

  const primary = s.tables?.[0];
  const rawData: Cell[][] = primary
    ? [primary.columns.map(HEAD), ...primary.rows.map((r) => r.map(cell))]
    : [[HEAD('Note')], [{ value: 'No tabular records for this scope' }]];

  const risk: Cell[][] = [
    [HEAD('Risk Metric'), HEAD('Value')],
    ...(s.kpis ?? []).map((k) => [{ value: k.label }, { value: k.value }]),
  ];

  const sheets: Array<{ sheet: string; data: Cell[][] }> = [
    { sheet: 'Executive Summary', data: summary },
    { sheet: 'Raw Data', data: rawData },
    { sheet: 'Risk Analysis', data: risk },
  ];
  if (config.include.audit_trail && s.audit_trail?.length) {
    const cols = Object.keys(s.audit_trail[0]);
    sheets.push({
      sheet: 'Audit Trail',
      data: [cols.map(HEAD), ...s.audit_trail.map((row) => cols.map((c) => cell(row[c])))],
    });
  }

  // write-excel-file's strict CellType<Value> constructor narrowing rejects
  // our permissive Cell shape — cast through unknown since the shape is valid
  // at runtime (mirrors builderExport.ts). The browser API returns a
  // { toBlob, toFile } handle; .toBlob() yields the Blob we hand back.
  return writeXlsxFile(sheets as unknown as Sheet<Blob>[]).toBlob();
}
