// web/src/modules/ai/explainabilityExport.ts
//
// Module 4.3 — Client-side PDF export.
//
// The spec acceptance says: "export produces a PDF suitable for
// regulator submission." That means the artifact must self-contain
// enough metadata that a regulator can read it standalone — model id +
// version + observed PD + every feature + trust signals + timestamp.
// The PDF is built entirely in the browser via jspdf + autotable
// (mirrors web/src/modules/reports/builder/builderExport.ts).

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

import type {
  ExplanationReport,
  FeatureImportanceReport,
  TrustSignalReport,
} from '@/lib/api';

interface ExportPayload {
  explanation: ExplanationReport;
  trust: TrustSignalReport | undefined;
  importance: FeatureImportanceReport | null;
}

function dateStamp(): string {
  return new Date().toISOString().slice(0, 10);
}

export function buildExplanationPdf(p: ExportPayload): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 40;
  let y = margin;

  // Header
  doc.setFontSize(16);
  doc.text('ZorEWS — Prediction Explainability', margin, y);
  y += 20;

  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text(
    `Prediction ${p.explanation.prediction_id}  ·  Tenant ${p.explanation.tenant_id}  ·  Generated ${p.explanation.generated_at}`,
    margin,
    y,
  );
  y += 14;
  doc.text(
    `Model ${p.explanation.model_id} (${p.explanation.model_version})  ·  Population base PD ${(p.explanation.base_pd_population * 100).toFixed(2)}%`,
    margin,
    y,
  );
  y += 20;

  // Headline
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(
    `Predicted PD: ${(p.explanation.pd * 100).toFixed(2)}%  ·  Band: ${p.explanation.band.toUpperCase()}`,
    margin,
    y,
  );
  y += 14;

  // Top features (the SPA card)
  autoTable(doc, {
    startY: y + 8,
    head: [['Rank', 'Feature', 'Group', 'Direction', 'Observed', 'Weight']],
    body: p.explanation.top_features.map((f, i) => [
      String(i + 1),
      f.display_name,
      f.group,
      f.direction === 'up' ? '↑ raises PD' : '↓ protective',
      f.observed_value,
      f.weight.toFixed(3),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [33, 64, 154] },
    styles: { fontSize: 9 },
  });
  // @ts-expect-error: lastAutoTable is provided by jspdf-autotable at runtime
  y = (doc.lastAutoTable?.finalY ?? y + 60) + 16;

  // Counterfactual
  doc.setFontSize(10);
  doc.text('Counterfactual:', margin, y);
  y += 14;
  doc.setFontSize(9);
  const cfText = doc.splitTextToSize(
    `${p.explanation.counterfactual.description}. PD would shift to ${p.explanation.counterfactual.resulting_band.toUpperCase()} (${(p.explanation.counterfactual.resulting_pd * 100).toFixed(2)}%).`,
    doc.internal.pageSize.getWidth() - 2 * margin,
  );
  doc.text(cfText, margin, y);
  y += cfText.length * 12 + 8;

  // Trust signals
  if (p.trust) {
    doc.setFontSize(11);
    doc.text(`Trust Signals — overall: ${p.trust.overall.toUpperCase()}`, margin, y);
    autoTable(doc, {
      startY: y + 8,
      head: [['Signal', 'Status', 'Value', 'Threshold']],
      body: p.trust.signals.map((s) => [
        s.signal.replace(/_/g, ' '),
        s.status.toUpperCase(),
        s.value,
        s.threshold,
      ]),
      theme: 'striped',
      headStyles: { fillColor: [33, 64, 154] },
      styles: { fontSize: 9 },
    });
    // @ts-expect-error: lastAutoTable is provided by jspdf-autotable at runtime
    y = (doc.lastAutoTable?.finalY ?? y + 60) + 16;
  }

  // Full feature importance (if loaded)
  if (p.importance && p.importance.features.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 120) {
      doc.addPage();
      y = margin;
    }
    doc.setFontSize(11);
    doc.text(`Full Feature Importance (${p.importance.total_features} features)`, margin, y);
    autoTable(doc, {
      startY: y + 8,
      head: [['Rank', 'Feature', 'Group', 'Direction', '|Weight|', 'Share']],
      body: p.importance.features.map((f) => [
        String(f.rank),
        f.display_name,
        f.group,
        f.direction === 'up' ? '↑' : '↓',
        f.abs_weight.toFixed(3),
        `${(f.pct_of_total * 100).toFixed(1)}%`,
      ]),
      theme: 'grid',
      headStyles: { fillColor: [33, 64, 154] },
      styles: { fontSize: 8 },
    });
  }

  // Footer with regulator-friendly attestation
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ZorEWS on ${p.explanation.generated_at}  ·  Page ${i}/${totalPages}  ·  Audit retention: 24 months`,
      margin,
      doc.internal.pageSize.getHeight() - 20,
    );
  }

  return doc;
}

export function downloadExplanationPdf(p: ExportPayload): void {
  const doc = buildExplanationPdf(p);
  const slug = p.explanation.prediction_id.replace(/[^a-z0-9-]/gi, '').slice(0, 16) || 'prediction';
  doc.save(`zorews-explanation-${slug}-${dateStamp()}.pdf`);
}
