// services/bff/src/reports/cases_detail_exporters.ts
//
// CSV / XLSX / PDF exporters for the Cases detail report. Each takes
// the row set + minimal meta + returns a Buffer (xlsx/pdf) or string
// (csv). Pure-ish — no IO except for what the libraries do internally.

import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import type { CaseRow, CasesDetailFilter } from './cases_detail_query';

export interface ExportMeta {
  tenant_id: string;
  generated_at: string;
  generated_by: string;
  filters: CasesDetailFilter;
}

const COLUMNS: Array<{ header: string; key: keyof CaseRow | 'borrower_name' | 'borrower_id'; width: number }> = [
  { header: 'Case ID',         key: 'case_id',                width: 18 },
  { header: 'Case Number',     key: 'case_number',            width: 16 },
  { header: 'Borrower ID',     key: 'borrower_id',            width: 12 },
  { header: 'Borrower',        key: 'borrower_name',          width: 24 },
  { header: 'Product',         key: 'product',                width: 18 },
  { header: 'Created Date',    key: 'created_at',             width: 22 },
  { header: 'Age (days)',      key: 'age_days',               width: 11 },
  { header: 'Age Bucket',      key: 'age_bucket',             width: 10 },
  { header: 'SLA Target',      key: 'sla_target_days',        width: 11 },
  { header: 'Breached',        key: 'is_breached',            width: 10 },
  { header: 'Severity',        key: 'severity',               width: 9 },
  { header: 'Priority',        key: 'priority',               width: 9 },
  { header: 'Status',          key: 'status',                 width: 16 },
  { header: 'Assigned To',     key: 'assigned_to',            width: 16 },
  { header: 'Assignee Name',   key: 'assignee_display_name',  width: 22 },
  { header: 'Branch',          key: 'branch',                 width: 12 },
  { header: 'Alert ID',        key: 'alert_id',               width: 14 },
];

function pluck(row: CaseRow, key: (typeof COLUMNS)[number]['key']): string | number | boolean | null {
  if (key === 'borrower_name') return row.borrower.name;
  if (key === 'borrower_id') return row.borrower.id;
  const v = (row as unknown as Record<string, unknown>)[key];
  if (v === null || v === undefined) return null;
  if (typeof v === 'boolean' || typeof v === 'number' || typeof v === 'string') return v;
  return String(v);
}

function csvEscape(v: string | number | boolean | null): string {
  if (v === null) return '';
  const s = typeof v === 'string' ? v : String(v);
  if (s.includes('"') || s.includes(',') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

// ── CSV ─────────────────────────────────────────────────────────────

export function exportCsv(rows: CaseRow[], _meta: ExportMeta): string {
  const header = COLUMNS.map((c) => csvEscape(c.header)).join(',');
  const lines = rows.map((r) =>
    COLUMNS.map((c) => csvEscape(pluck(r, c.key))).join(','),
  );
  // CRLF line ending — Excel-on-Windows safe; macOS handles either.
  return [header, ...lines].join('\r\n') + '\r\n';
}

// ── XLSX ────────────────────────────────────────────────────────────

export async function exportXlsx(rows: CaseRow[], meta: ExportMeta): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = `APEX EWS · ${meta.generated_by}`;
  wb.created = new Date(meta.generated_at);

  // Sheet 1 — Cases
  const sheet = wb.addWorksheet('Cases', { views: [{ state: 'frozen', ySplit: 1 }] });
  sheet.columns = COLUMNS.map((c) => ({
    header: c.header,
    key: String(c.key),
    width: c.width,
  }));
  // Header row styling
  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFE5E7EB' }, // slate-200
  };
  for (const r of rows) {
    const rowVals: Record<string, string | number | boolean | null> = {};
    for (const c of COLUMNS) rowVals[String(c.key)] = pluck(r, c.key);
    sheet.addRow(rowVals);
  }
  // Tint breached rows rose-50
  sheet.eachRow((row, idx) => {
    if (idx === 1) return;
    const isBreached = row.getCell('is_breached').value === true;
    if (isBreached) {
      row.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } };
      });
    }
  });

  // Sheet 2 — Filters / metadata (audit-friendly, BAC §3.1.8)
  const meta2 = wb.addWorksheet('Filters');
  meta2.columns = [
    { header: 'Field', key: 'field', width: 24 },
    { header: 'Value', key: 'value', width: 60 },
  ];
  meta2.getRow(1).font = { bold: true };
  meta2.addRow({ field: 'Tenant', value: meta.tenant_id });
  meta2.addRow({ field: 'Generated at', value: meta.generated_at });
  meta2.addRow({ field: 'Generated by', value: meta.generated_by });
  meta2.addRow({ field: 'Row count', value: rows.length });
  meta2.addRow({ field: '', value: '' });
  meta2.addRow({ field: '— Filters applied —', value: '' });
  for (const [k, v] of Object.entries(meta.filters)) {
    meta2.addRow({ field: k, value: v == null ? '(none)' : JSON.stringify(v) });
  }

  const out = await wb.xlsx.writeBuffer();
  return Buffer.from(out);
}

// ── PDF ─────────────────────────────────────────────────────────────

export async function exportPdf(rows: CaseRow[], meta: ExportMeta): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 30 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Title block
    doc.fontSize(14).font('Helvetica-Bold').text(`Cases Report — ${meta.tenant_id}`);
    doc.moveDown(0.2);
    doc
      .fontSize(8)
      .font('Helvetica')
      .text(`Generated by ${meta.generated_by} · ${new Date(meta.generated_at).toLocaleString()}`);
    doc.text(`Rows: ${rows.length}`);
    doc.moveDown(0.5);

    // PDF realistic columns subset (PDF table can't fit all 17 wide). The
    // CSV/XLSX have everything; PDF prioritises the readable subset.
    const PDF_COLS: Array<{ header: string; pluck: (r: CaseRow) => string; w: number }> = [
      { header: 'Case #',     pluck: (r) => r.case_number,                                w: 75 },
      { header: 'Borrower',   pluck: (r) => r.borrower.name ?? '—',                       w: 110 },
      { header: 'Product',    pluck: (r) => r.product ?? '—',                             w: 80 },
      { header: 'Created',    pluck: (r) => new Date(r.created_at).toLocaleDateString(),  w: 70 },
      { header: 'Age',        pluck: (r) => r.age_days.toFixed(1) + 'd',                  w: 38 },
      { header: 'Bucket',     pluck: (r) => r.age_bucket,                                 w: 50 },
      { header: 'SLA',        pluck: (r) => (r.sla_target_days != null ? r.sla_target_days + 'd' : '—'), w: 38 },
      { header: 'Breach',     pluck: (r) => (r.is_breached ? 'YES' : 'no'),               w: 38 },
      { header: 'Severity',   pluck: (r) => r.severity,                                   w: 50 },
      { header: 'Status',     pluck: (r) => r.status,                                     w: 80 },
      { header: 'Assigned',   pluck: (r) => r.assigned_to ?? '—',                         w: 75 },
      { header: 'Branch',     pluck: (r) => r.branch ?? '—',                              w: 60 },
    ];

    const drawHeader = () => {
      let x = doc.x;
      const y = doc.y;
      doc.font('Helvetica-Bold').fontSize(8);
      for (const c of PDF_COLS) {
        doc.text(c.header, x, y, { width: c.w, lineBreak: false });
        x += c.w;
      }
      doc.font('Helvetica').fontSize(8);
      doc.moveTo(doc.page.margins.left, y + 12).lineTo(doc.page.width - doc.page.margins.right, y + 12).stroke();
      doc.y = y + 14;
    };
    drawHeader();

    for (const r of rows) {
      // Page break + header repeat if we're close to the bottom
      if (doc.y > doc.page.height - doc.page.margins.bottom - 24) {
        doc.addPage({ size: 'A4', layout: 'landscape', margin: 30 });
        drawHeader();
      }
      let x = doc.page.margins.left;
      const y = doc.y;
      const rowFill = r.is_breached ? '#FEE2E2' : null;
      if (rowFill) {
        doc
          .rect(doc.page.margins.left, y - 1, doc.page.width - doc.page.margins.left - doc.page.margins.right, 12)
          .fill(rowFill);
        doc.fillColor('black');
      }
      for (const c of PDF_COLS) {
        doc.text(c.pluck(r), x, y, { width: c.w, ellipsis: true, lineBreak: false });
        x += c.w;
      }
      doc.y = y + 12;
    }

    // Footer on last page
    doc
      .fontSize(7)
      .fillColor('gray')
      .text(
        `BAC §3.1.8 · APEX EWS · This report is confidential — do not redistribute`,
        doc.page.margins.left,
        doc.page.height - doc.page.margins.bottom - 12,
        { width: doc.page.width - doc.page.margins.left - doc.page.margins.right, align: 'center' },
      );
    doc.fillColor('black');

    doc.end();
  });
}

// ── Row caps per format (BAC §3.1.8 best practice) ─────────────────

export const ROW_CAP: Record<'csv' | 'xlsx' | 'pdf', number> = {
  csv: 50_000,
  xlsx: 50_000,
  pdf: 5_000,
};
