// services/bff/src/reports/xlsx.ts
//
// Renders a ReportPayload to an .xlsx workbook using exceljs. Each report
// gets a multi-sheet workbook so analysts can pivot/copy without re-shaping
// the data. Headers use the brand-blue fill from the design tokens for
// quick visual scanning.

import ExcelJS from 'exceljs';
import type {
  AlertActivityReport,
  CaseOutcomesReport,
  PortfolioSnapshot,
  RbiSummaryReport,
  ReportPayload,
} from './types';

const HEADER_FILL: ExcelJS.FillPattern = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FF0D2B6A' }, // brand-blue
};
const HEADER_FONT: Partial<ExcelJS.Font> = { color: { argb: 'FFFFFFFF' }, bold: true };

interface XlsxMeta {
  generated_by: string;
  tenant?: string;
}

function styleHeaderRow(row: ExcelJS.Row): void {
  row.font = HEADER_FONT;
  row.fill = HEADER_FILL;
  row.alignment = { vertical: 'middle', horizontal: 'left' };
}

function metaRows(payload: ReportPayload, meta: XlsxMeta): Array<[string, string | number]> {
  return [
    ['Report type', payload.type],
    ['Period', payload.period],
    ['Period start', payload.period_start],
    ['Period end', payload.period_end],
    ['Generated at', payload.generated_at],
    ['Generated by', meta.generated_by],
    ['Tenant', meta.tenant ?? 'apex-prototype'],
  ];
}

function addMetaSheet(wb: ExcelJS.Workbook, payload: ReportPayload, meta: XlsxMeta): void {
  const ws = wb.addWorksheet('Metadata');
  ws.columns = [
    { header: 'Field', key: 'field', width: 24 },
    { header: 'Value', key: 'value', width: 40 },
  ];
  styleHeaderRow(ws.getRow(1));
  for (const [field, value] of metaRows(payload, meta)) {
    ws.addRow({ field, value });
  }
}

function snapshotXlsx(wb: ExcelJS.Workbook, r: PortfolioSnapshot): void {
  const ws = wb.addWorksheet('Snapshot');
  ws.columns = [
    { header: 'Metric', key: 'metric', width: 30 },
    { header: 'Value', key: 'value', width: 18 },
  ];
  styleHeaderRow(ws.getRow(1));
  const rows: Array<[string, number]> = [
    ['Customers monitored', r.customers_monitored],
    ['High-risk customers', r.high_risk_customers],
    ['High-risk %', r.high_risk_pct],
    ['Total exposure (KES)', r.total_exposure_kes],
    ['Alerts open', r.alerts_open],
    ['Cases in progress', r.cases_in_progress],
    ['Stage 1 — performing', r.stage_distribution.stage_1],
    ['Stage 2 — under-performing', r.stage_distribution.stage_2],
    ['Stage 3 — non-performing', r.stage_distribution.stage_3],
    ['ECL (KES)', r.expected_credit_loss_kes],
    ['NPA %', r.npa_pct],
  ];
  for (const [metric, value] of rows) ws.addRow({ metric, value });
  // Format the currency columns as thousands-separated.
  ws.getColumn('value').numFmt = '#,##0.00';
}

function alertActivityXlsx(wb: ExcelJS.Workbook, r: AlertActivityReport): void {
  const summary = wb.addWorksheet('Summary');
  summary.columns = [
    { header: 'Metric', key: 'metric', width: 28 },
    { header: 'Value', key: 'value', width: 14 },
  ];
  styleHeaderRow(summary.getRow(1));
  const summaryRows: Array<[string, number]> = [
    ['Raised total', r.raised_total],
    ['Closed total', r.closed_total],
    ['Open at end', r.open_at_end],
    ['Avg minutes to ack', r.avg_minutes_to_ack],
    ['Avg minutes to close', r.avg_minutes_to_close],
    ['Raised — critical', r.raised_by_severity.critical],
    ['Raised — high', r.raised_by_severity.high],
    ['Raised — medium', r.raised_by_severity.medium],
    ['Raised — low', r.raised_by_severity.low],
  ];
  for (const [metric, value] of summaryRows) summary.addRow({ metric, value });

  const top = wb.addWorksheet('Top rules');
  top.columns = [
    { header: 'Rule ID', key: 'rule_id', width: 14 },
    { header: 'Rule name', key: 'rule_name', width: 36 },
    { header: 'Firings', key: 'firings', width: 12 },
  ];
  styleHeaderRow(top.getRow(1));
  for (const t of r.top_rules) top.addRow(t);
}

function caseOutcomesXlsx(wb: ExcelJS.Workbook, r: CaseOutcomesReport): void {
  const summary = wb.addWorksheet('Summary');
  summary.columns = [
    { header: 'Metric', key: 'metric', width: 28 },
    { header: 'Value', key: 'value', width: 14 },
  ];
  styleHeaderRow(summary.getRow(1));
  const rows: Array<[string, number]> = [
    ['Cases opened', r.cases_opened],
    ['Cases closed', r.cases_closed],
    ['Cured (full recovery)', r.outcomes.cured],
    ['Cured (temporary)', r.outcomes.cured_temp],
    ['Defaulted', r.outcomes.defaulted],
    ['Avg days to close', r.avg_days_to_close],
  ];
  for (const [metric, value] of rows) summary.addRow({ metric, value });

  const officers = wb.addWorksheet('Top officers');
  officers.columns = [
    { header: 'Officer ID', key: 'officer_id', width: 16 },
    { header: 'Cases closed', key: 'cases_closed', width: 14 },
  ];
  styleHeaderRow(officers.getRow(1));
  for (const o of r.top_officers) officers.addRow(o);

  const products = wb.addWorksheet('By product');
  products.columns = [
    { header: 'Product', key: 'product', width: 18 },
    { header: 'Cases closed', key: 'cases_closed', width: 14 },
  ];
  styleHeaderRow(products.getRow(1));
  for (const p of r.product_breakdown) products.addRow(p);
}

function rbiXlsx(wb: ExcelJS.Workbook, r: RbiSummaryReport): void {
  const summary = wb.addWorksheet('Summary');
  summary.columns = [
    { header: 'Metric', key: 'metric', width: 28 },
    { header: 'Value', key: 'value', width: 18 },
  ];
  styleHeaderRow(summary.getRow(1));
  const rows: Array<[string, number]> = [
    ['ECL (KES)', r.ecl_kes],
    ['ECL Δ qoq (KES)', r.ecl_qoq_delta_kes],
    ['NPA %', r.npa_pct],
  ];
  for (const [metric, value] of rows) summary.addRow({ metric, value });
  summary.getColumn('value').numFmt = '#,##0.00';

  const sectors = wb.addWorksheet('Sector exposure');
  sectors.columns = [
    { header: 'Sector', key: 'sector', width: 24 },
    { header: 'Exposure (KES)', key: 'exposure_kes', width: 18 },
    { header: 'Share %', key: 'share_pct', width: 12 },
  ];
  styleHeaderRow(sectors.getRow(1));
  for (const s of r.sector_exposure) sectors.addRow(s);
  sectors.getColumn('exposure_kes').numFmt = '#,##0.00';

  const bands = wb.addWorksheet('Risk bands');
  bands.columns = [
    { header: 'Band', key: 'band', width: 14 },
    { header: 'Accounts', key: 'accounts', width: 12 },
    { header: 'Share %', key: 'share_pct', width: 12 },
  ];
  styleHeaderRow(bands.getRow(1));
  for (const b of r.risk_band_distribution) bands.addRow(b);

  const conc = wb.addWorksheet('Top concentrations');
  conc.columns = [
    { header: 'Customer ID', key: 'customer_id', width: 16 },
    { header: 'Name', key: 'name', width: 28 },
    { header: 'Exposure (KES)', key: 'exposure_kes', width: 18 },
  ];
  styleHeaderRow(conc.getRow(1));
  for (const c of r.top_concentrations) conc.addRow(c);
  conc.getColumn('exposure_kes').numFmt = '#,##0.00';
}

export async function reportToXlsx(payload: ReportPayload, meta: XlsxMeta): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'APEX EWS';
  wb.created = new Date();
  wb.title = `APEX EWS · ${payload.type} · ${payload.period}`;

  addMetaSheet(wb, payload, meta);
  switch (payload.type) {
    case 'snapshot':
      snapshotXlsx(wb, payload);
      break;
    case 'alerts':
      alertActivityXlsx(wb, payload);
      break;
    case 'cases':
      caseOutcomesXlsx(wb, payload);
      break;
    case 'rbi':
      rbiXlsx(wb, payload);
      break;
  }
  const arrayBuffer = await wb.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}
