import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Download } from 'lucide-react';
import { PageHeader } from '@/components/layout/PageHeader';
import { Panel, Badge, DataTable, type Column, type BadgeTone } from '@/components/ui';
import { api } from '@/lib/api';

const FORMAT_TONE: Record<string, BadgeTone> = {
  pdf: 'danger', xlsx: 'success', csv: 'blue', docx: 'purple',
};

export function ExportHistoryPage() {
  const [moduleFilter, setModuleFilter] = useState<string>('');
  const [formatFilter, setFormatFilter] = useState<string>('');
  const { data, isLoading } = useQuery({
    queryKey: ['exports.history', moduleFilter, formatFilter],
    queryFn: () => api.exportsHistory({ module: moduleFilter || undefined, format: formatFilter || undefined }),
  });
  // DataTable requires each row to carry an `id`; server records key on export_id.
  const rows = (data?.items ?? []).map((r) => ({ ...r, id: r.export_id }));

  const columns: Column<(typeof rows)[number]>[] = [
    { key: 'title', header: 'Report', render: (r) => <span className="font-medium">{r.title}</span> },
    { key: 'module', header: 'Module', render: (r) => <span className="text-xs">{r.module}</span> },
    { key: 'report_type', header: 'Type', render: (r) => <Badge tone="neutral">{r.report_type}</Badge> },
    { key: 'format', header: 'Format', render: (r) => <Badge tone={FORMAT_TONE[r.format] ?? 'neutral'}>{r.format.toUpperCase()}</Badge> },
    { key: 'generated_by', header: 'Generated By', render: (r) => <span className="text-xs">{r.generated_by}</span> },
    { key: 'generated_at', header: 'When', render: (r) => <span className="text-xs">{new Date(r.generated_at).toLocaleString()}</span> },
    { key: 'record_count', header: 'Records', align: 'right', render: (r) => <span className="tabular-nums">{r.record_count}</span> },
    { key: 'status', header: 'Status', render: (r) => <Badge tone={r.status === 'completed' ? 'success' : 'danger'}>{r.status}</Badge> },
    {
      key: 'download', header: '', render: (r) => r.has_artifact
        ? <a data-testid="export-download" href={`/v1/exports/${r.export_id}/download`} className="inline-flex items-center gap-1 text-action text-xs hover:underline"><Download size={13} /> Download</a>
        : <span className="text-2xs text-muted">re-export from module</span>,
    },
  ];

  return (
    <div data-testid="export-history-page">
      <PageHeader title="Export History Center" subtitle="Every report exported across ZorEWS — with re-download for stored artifacts." />
      <Panel>
        <div className="flex gap-2 mb-3">
          <input className="input" placeholder="Filter module…" value={moduleFilter} onChange={(e) => setModuleFilter(e.target.value)} data-testid="export-history-module" />
          <select className="input" value={formatFilter} onChange={(e) => setFormatFilter(e.target.value)} data-testid="export-history-format">
            <option value="">All formats</option>
            <option value="pdf">PDF</option><option value="xlsx">Excel</option>
            <option value="csv">CSV</option><option value="docx">Word</option>
          </select>
        </div>
        {isLoading ? <p className="caption">Loading…</p> : <DataTable columns={columns} data={rows} />}
      </Panel>
    </div>
  );
}
