// services/bff/__tests__/admin_config_summary.test.ts
//
// T6 M13.9 — Admin config printable summary export.

import request from 'supertest';
import { renderConfigSummary } from '../src/admin_config_summary';
import { InMemoryConfigStore } from '../src/admin_config';
import { makeApp } from '../src/server';
import { StaticSource } from '../src/source';
import { StubEvaluator } from '../src/score';
import { StubRiskProfileSource } from '../src/risk_profile';
import { UnavailableCaseActionSink } from '../src/case_action';

const NOW = new Date('2026-05-14T12:00:00.000Z');
const TH_BIL = { 'X-Tenant-ID': 'BIL', 'X-Channel': 'API' };

// ─── renderConfigSummary — pure ──────────────────────────────────────

describe('M13.9 — renderConfigSummary — empty + shape', () => {
  test('no entries → header + footer + zero counts', () => {
    const text = renderConfigSummary('BIL', [], {
      generated_at: NOW.toISOString(),
      generated_by: 'alice',
    });
    expect(text).toContain('ADMIN CONFIG — TENANT SUMMARY');
    expect(text).toContain('Tenant            : BIL');
    expect(text).toContain('Generated at      : 2026-05-14T12:00:00.000Z');
    expect(text).toContain('Generated by      : alice');
    expect(text).toContain('Total keys        : 0');
    expect(text).toContain('Tenant overrides  : 0');
    expect(text).toContain('Platform defaults : 0');
    expect(text).toContain('END OF SUMMARY');
  });
});

describe('M13.9 — renderConfigSummary — populated', () => {
  test('all-default entries render with (default) tag + no override metadata', () => {
    const store = new InMemoryConfigStore();
    const entries = store.list('BIL');
    const text = renderConfigSummary('BIL', entries, {
      generated_at: NOW.toISOString(),
      generated_by: 'alice',
    });
    expect(text).toContain(`Tenant overrides  : 0`);
    expect(text).toContain(`Platform defaults : ${entries.length}`);
    expect(text).toContain('(default)');
    // No (override) markers anywhere.
    expect(text.match(/\(override\)/g)).toBeNull();
  });

  test('overrides render with (override) tag + set timestamp + actor', () => {
    const store = new InMemoryConfigStore();
    store.set('BIL', 'alerts.red_sla_hours', 2, 'alice', NOW);
    const entries = store.list('BIL');
    const text = renderConfigSummary('BIL', entries, {
      generated_at: NOW.toISOString(),
      generated_by: 'admin',
    });
    expect(text).toContain('Tenant overrides  : 1');
    expect(text).toContain('(override)');
    expect(text).toContain('alerts.red_sla_hours');
    expect(text).toContain('value : 2');
    expect(text).toContain(`set   : ${NOW.toISOString()}  by alice`);
  });

  test('entries grouped under category section headers', () => {
    const store = new InMemoryConfigStore();
    const entries = store.list('BIL');
    const text = renderConfigSummary('BIL', entries, {
      generated_at: NOW.toISOString(),
      generated_by: 'admin',
    });
    // 5 categories: alerts, notifications, reporting, scoring, features.
    // Each has ≥ 1 platform key, so each header should appear.
    expect(text).toContain('ALERTS');
    expect(text).toContain('NOTIFICATIONS');
  });

  test('keys sorted alphabetically within a category', () => {
    const store = new InMemoryConfigStore();
    const entries = store.list('BIL');
    const text = renderConfigSummary('BIL', entries, {
      generated_at: NOW.toISOString(),
      generated_by: 'admin',
    });
    // Within ALERTS section, the keys should be sorted asc.
    const alertsStart = text.indexOf('ALERTS');
    const nextSection = text.indexOf('NOTIFICATIONS');
    expect(alertsStart).toBeGreaterThan(0);
    expect(nextSection).toBeGreaterThan(alertsStart);
    const alertsBlock = text.slice(alertsStart, nextSection);
    // Order: alerts.orange_sla_hours < alerts.red_sla_hours < alerts.yellow_sla_hours
    const orangeIdx = alertsBlock.indexOf('alerts.orange_sla_hours');
    const redIdx = alertsBlock.indexOf('alerts.red_sla_hours');
    const yellowIdx = alertsBlock.indexOf('alerts.yellow_sla_hours');
    expect(orangeIdx).toBeGreaterThan(-1);
    expect(redIdx).toBeGreaterThan(orangeIdx);
    expect(yellowIdx).toBeGreaterThan(redIdx);
  });
});

describe('M13.9 — value formatting', () => {
  test('booleans render as true/false; numbers raw; strings as-is', () => {
    const store = new InMemoryConfigStore();
    store.set('BIL', 'notifications.email.enabled', false, 'alice', NOW);
    store.set('BIL', 'alerts.red_sla_hours', 1.5, 'alice', NOW);
    const entries = store.list('BIL');
    const text = renderConfigSummary('BIL', entries, {
      generated_at: NOW.toISOString(),
      generated_by: 'admin',
    });
    expect(text).toContain('value : false');
    expect(text).toContain('value : 1.5');
  });
});

// ─── Route — GET /v1/admin/config/summary.txt ────────────────────────

function makeSummaryApp(role = 'admin') {
  const configStore = new InMemoryConfigStore();
  const built = makeApp({
    source: new StaticSource([]),
    evaluator: new StubEvaluator(),
    riskProfile: new StubRiskProfileSource(),
    caseAction: new UnavailableCaseActionSink(),
    configStore,
    now: () => NOW,
    getRole: () => role,
  });
  return { ...built, configStore };
}

describe('M13.9 — GET /v1/admin/config/summary.txt', () => {
  test('empty tenant → 200 text/plain with shell + default counts', async () => {
    const { app } = makeSummaryApp('admin');
    const r = await request(app)
      .get('/v1/admin/config/summary.txt')
      .set(TH_BIL)
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(200);
    expect(r.headers['content-type']).toContain('text/plain');
    expect(r.headers['content-disposition']).toContain('BIL');
    expect(r.text).toContain('ADMIN CONFIG — TENANT SUMMARY');
    expect(r.text).toContain('Tenant            : BIL');
    expect(r.text).toContain('Generated by      : alice');
  });

  test('after setting an override, summary.txt surfaces it', async () => {
    const { app, configStore } = makeSummaryApp('admin');
    configStore.set('BIL', 'alerts.red_sla_hours', 2, 'alice', NOW);
    const r = await request(app)
      .get('/v1/admin/config/summary.txt')
      .set(TH_BIL)
      .set('x-apex-user', 'admin');
    expect(r.status).toBe(200);
    expect(r.text).toContain('Tenant overrides  : 1');
    expect(r.text).toContain('alerts.red_sla_hours');
    expect(r.text).toContain('(override)');
    expect(r.text).toContain('by alice');
  });

  test('non-allowed role → 403', async () => {
    const { app } = makeSummaryApp('case_owner');
    const r = await request(app)
      .get('/v1/admin/config/summary.txt')
      .set(TH_BIL)
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(403);
  });

  test('cross-tenant: BIL override invisible to BANK_DEMO', async () => {
    const { app, configStore } = makeSummaryApp('admin');
    configStore.set('BIL', 'alerts.red_sla_hours', 2, 'alice', NOW);
    const r = await request(app)
      .get('/v1/admin/config/summary.txt')
      .set('X-Tenant-ID', 'BANK_DEMO')
      .set('X-Channel', 'API')
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(200);
    expect(r.text).toContain('Tenant overrides  : 0');
  });

  test('M13.1 GET /v1/admin/config still works (summary route is additive)', async () => {
    const { app } = makeSummaryApp('admin');
    const r = await request(app).get('/v1/admin/config').set(TH_BIL);
    expect(r.status).toBe(200);
    // JSON envelope, not text/plain.
    expect(r.headers['content-type']).toContain('application/json');
  });
});
