// services/bff/__tests__/audit_evidence_summary.test.ts
//
// T6 M15.4 — Evidence package summary export.

import request from 'supertest';
import { renderEvidenceSummary } from '../src/audit_evidence_summary';
import {
  InMemoryEvidencePackageStore,
  type EvidencePackage,
} from '../src/audit_evidence';
import { type AuditEvent } from '../src/audit_trail';
import { makeApp } from '../src/server';
import { StaticSource } from '../src/source';
import { StubEvaluator } from '../src/score';
import { StubRiskProfileSource } from '../src/risk_profile';
import { UnavailableCaseActionSink } from '../src/case_action';

const NOW = new Date('2026-05-05T20:00:00.000Z');
const TH_BIL = { 'X-Tenant-ID': 'BIL', 'X-Channel': 'API' };

function mkEvent(o: Partial<AuditEvent> & { ts: string; action: AuditEvent['action'] }): AuditEvent {
  return {
    event_id: o.event_id ?? `evt-${Math.random().toString(36).slice(2, 8)}`,
    ts: o.ts,
    tenant_id: o.tenant_id ?? 'BIL',
    actor_username: o.actor_username ?? 'admin',
    actor_role: o.actor_role ?? 'admin',
    action: o.action,
    resource_type: o.resource_type ?? 'config',
    resource_id: o.resource_id ?? 'CFG-1',
    outcome: o.outcome ?? 'success',
    severity: o.severity ?? 'info',
    correlation_id: o.correlation_id ?? null,
    ip_address: o.ip_address ?? null,
    metadata: o.metadata ?? {},
    hash: o.hash ?? 'abc123',
    prev_hash: o.prev_hash ?? 'GENESIS',
  };
}

function mkPackage(over: Partial<EvidencePackage> = {}): EvidencePackage {
  const events: AuditEvent[] =
    over.events ??
    [
      mkEvent({
        ts: '2026-05-05T19:00:00.000Z',
        action: 'config.update',
        actor_username: 'taniya',
      }),
      mkEvent({
        ts: '2026-05-05T19:05:00.000Z',
        action: 'rule.create',
        outcome: 'failure',
        severity: 'warning',
      }),
      mkEvent({
        ts: '2026-05-05T19:01:00.000Z',
        action: 'config.update',
        actor_username: 'compliance.lead',
      }),
    ];
  return {
    package_id: 'EVD-BIL-2026-05-05-1',
    tenant_id: 'BIL',
    generated_at: '2026-05-05T20:00:00.000Z',
    generated_by: 'admin',
    filters: {},
    event_count: events.length,
    events,
    integrity: {
      chain_verified: true,
      chain_last_hash: 'beefcafe',
      first_event_hash: 'aa11',
      last_event_hash: 'zz99',
    },
    size_bytes: 1234,
    ...over,
  };
}

function makeSummaryApp(role = 'admin') {
  const store = new InMemoryEvidencePackageStore();
  const built = makeApp({
    source: new StaticSource([]),
    evaluator: new StubEvaluator(),
    riskProfile: new StubRiskProfileSource(),
    caseAction: new UnavailableCaseActionSink(),
    evidenceStore: store,
    now: () => NOW,
    getRole: () => role,
  });
  return { ...built, store };
}

// ─── Pure renderer ────────────────────────────────────────────────────

describe('M15.4 — renderEvidenceSummary (pure)', () => {
  test('header carries package_id, tenant, generated_at/by, counts', () => {
    const out = renderEvidenceSummary(mkPackage());
    expect(out).toContain('EVIDENCE PACKAGE');
    expect(out).toContain('Package ID    : EVD-BIL-2026-05-05-1');
    expect(out).toContain('Tenant        : BIL');
    expect(out).toContain('Generated by  : admin');
    expect(out).toContain('Event count   : 3');
    expect(out).toContain('Size (bytes)  : 1234');
  });

  test('integrity PASS block when chain_verified=true', () => {
    const out = renderEvidenceSummary(mkPackage());
    expect(out).toContain('Chain verified: PASS');
    expect(out).toContain('Chain anchor  : beefcafe');
    expect(out).toContain('First event   : aa11');
    expect(out).toContain('Last event    : zz99');
    expect(out).not.toContain('Broken at');
  });

  test('integrity FAIL block surfaces broken_at', () => {
    const pkg = mkPackage({
      integrity: {
        chain_verified: false,
        chain_last_hash: 'broken',
        first_event_hash: null,
        last_event_hash: null,
        broken_at: {
          index: 2,
          event_id: 'evt-bad',
          expected_hash: 'aa',
          actual_hash: 'bb',
          reason: 'hash_mismatch',
        },
      },
    });
    const out = renderEvidenceSummary(pkg);
    expect(out).toContain('Chain verified: FAIL');
    expect(out).toContain('Broken at     : index=2 event=evt-bad reason=hash_mismatch');
  });

  test('filter section says "no filters" when filters empty', () => {
    const out = renderEvidenceSummary(mkPackage({ filters: {} }));
    expect(out).toContain('FILTERS APPLIED');
    expect(out).toContain('(no filters');
  });

  test('filter section lists each set filter on its own line', () => {
    const out = renderEvidenceSummary(
      mkPackage({
        filters: {
          since: '2026-05-05T00:00:00Z',
          actor_username: 'taniya',
          action: 'config.update',
        },
      }),
    );
    expect(out).toContain('since:');
    expect(out).toContain('2026-05-05T00:00:00Z');
    expect(out).toContain('actor_username:');
    expect(out).toContain('taniya');
    expect(out).toContain('action:');
    expect(out).toContain('config.update');
    expect(out).not.toContain('(no filters');
  });

  test('counts-by-action descending', () => {
    const out = renderEvidenceSummary(mkPackage());
    const lines = out.split('\n');
    const actionsHeaderIdx = lines.findIndex((l) => l.includes('By action:'));
    // 2 config.update + 1 rule.create — config.update should appear first
    const subset = lines.slice(actionsHeaderIdx + 1, actionsHeaderIdx + 5).join('\n');
    expect(subset.indexOf('config.update')).toBeLessThan(subset.indexOf('rule.create'));
  });

  test('counts-by-outcome includes success and failure', () => {
    const out = renderEvidenceSummary(mkPackage());
    expect(out).toContain('By outcome:');
    expect(out).toMatch(/success\s+2/);
    expect(out).toMatch(/failure\s+1/);
  });

  test('events block sorted oldest-first', () => {
    const out = renderEvidenceSummary(mkPackage());
    const eventsHeaderIdx = out.indexOf('EVENTS (oldest first)');
    const after = out.slice(eventsHeaderIdx);
    const a = after.indexOf('2026-05-05T19:00:00.000Z'); // first inserted, earliest ts
    const b = after.indexOf('2026-05-05T19:01:00.000Z'); // third inserted, middle ts
    const c = after.indexOf('2026-05-05T19:05:00.000Z'); // second inserted, latest ts
    expect(a).toBeGreaterThan(0);
    expect(a).toBeLessThan(b);
    expect(b).toBeLessThan(c);
  });

  test('empty events package renders "(no events captured)"', () => {
    const out = renderEvidenceSummary(
      mkPackage({
        events: [],
        event_count: 0,
        integrity: {
          chain_verified: true,
          chain_last_hash: 'genesis',
          first_event_hash: null,
          last_event_hash: null,
        },
      }),
    );
    expect(out).toContain('(no events captured)');
  });

  test('output ends with END OF SUMMARY footer', () => {
    const out = renderEvidenceSummary(mkPackage());
    expect(out.trimEnd().endsWith('─'.repeat(72))).toBe(true);
    expect(out).toContain('END OF SUMMARY');
  });

  test('summary is plain ASCII-ish + box-drawing only — no JSON braces', () => {
    const out = renderEvidenceSummary(mkPackage());
    expect(out).not.toContain('{');
    expect(out).not.toContain('}');
  });
});

// ─── Route ────────────────────────────────────────────────────────────

describe('M15.4 — GET /v1/audit/evidence/:package_id/summary.txt', () => {
  test('happy: 200 text/plain with header', async () => {
    const { app, store } = makeSummaryApp('admin');
    // Manually inject a package — InMemoryEvidencePackageStore doesn't
    // expose a put() on the public interface, but we know the impl uses
    // build() against the audit trail to construct a real package. For
    // this route test, easier to bypass and seed the underlying state.
    // The store's createForTenant() requires the trail; skip by using
    // the tenant trail through the standard build path.

    // Use the existing POST /v1/audit/evidence route to create a real
    // package against the empty trail.
    const create = await request(app)
      .post('/v1/audit/evidence')
      .set(TH_BIL)
      .send({});
    expect(create.status).toBe(201);
    const id = create.body.body.package_id;

    const r = await request(app)
      .get(`/v1/audit/evidence/${id}/summary.txt`)
      .set(TH_BIL);
    expect(r.status).toBe(200);
    expect(r.headers['content-type']).toContain('text/plain');
    expect(r.headers['content-disposition']).toContain(`${id}.summary.txt`);
    expect(r.text).toContain('EVIDENCE PACKAGE');
    expect(r.text).toContain(`Package ID    : ${id}`);
    void store;
  });

  test('unknown package → 404 (JSON envelope, not text)', async () => {
    const { app } = makeSummaryApp('admin');
    const r = await request(app)
      .get('/v1/audit/evidence/EVD-NOPE/summary.txt')
      .set(TH_BIL);
    expect(r.status).toBe(404);
    expect(r.body.error.code).toBe('EWS_404_unknown_package');
  });

  test('cross-tenant: BANK_DEMO cannot fetch BIL package summary', async () => {
    const { app } = makeSummaryApp('admin');
    const create = await request(app)
      .post('/v1/audit/evidence')
      .set(TH_BIL)
      .send({});
    const id = create.body.body.package_id;
    const r = await request(app)
      .get(`/v1/audit/evidence/${id}/summary.txt`)
      .set('X-Tenant-ID', 'BANK_DEMO')
      .set('X-Channel', 'API');
    expect(r.status).toBe(404);
  });

  test('non-allowed role → 403', async () => {
    const { app } = makeSummaryApp('case_owner');
    const r = await request(app)
      .get('/v1/audit/evidence/anything/summary.txt')
      .set(TH_BIL);
    expect(r.status).toBe(403);
  });

  test('M15.3 single-package GET still works (literal summary.txt did not shadow)', async () => {
    const { app } = makeSummaryApp('admin');
    const create = await request(app)
      .post('/v1/audit/evidence')
      .set(TH_BIL)
      .send({});
    const id = create.body.body.package_id;
    const r = await request(app).get(`/v1/audit/evidence/${id}`).set(TH_BIL);
    expect(r.status).toBe(200);
    expect(r.body.body.package_id).toBe(id);
    // Response is JSON envelope, not the text summary
    expect(r.headers['content-type']).toContain('application/json');
  });
});
