// services/bff/__tests__/model_performance_summary.test.ts
//
// T6 M7.6 — Model performance summary printable text export.

import request from 'supertest';
import { renderPerformanceSummary } from '../src/model_performance_summary';
import type { ModelPerformanceSummary } from '../src/model_performance';
import {
  InMemoryModelPerformanceStore,
} from '../src/model_performance';
import { defaultAiModelRegistry } from '../src/ai_model_registry';
import { makeApp } from '../src/server';
import { StaticSource } from '../src/source';
import { StubEvaluator } from '../src/score';
import { StubRiskProfileSource } from '../src/risk_profile';
import { UnavailableCaseActionSink } from '../src/case_action';

const NOW = new Date('2026-05-14T12:00:00.000Z');
const TH_BIL = { 'X-Tenant-ID': 'BIL', 'X-Channel': 'API' };

function mkSummary(
  overrides: Partial<ModelPerformanceSummary> = {},
): ModelPerformanceSummary {
  return {
    tenant_id: overrides.tenant_id ?? 'BIL',
    model_id: overrides.model_id ?? 'pd_xgb_v3',
    sample_size: overrides.sample_size ?? 0,
    metrics: overrides.metrics ?? {
      precision: null,
      recall: null,
      auc: null,
      drift_score: null,
      calibration_err: null,
    },
  };
}

// ─── renderPerformanceSummary — pure ─────────────────────────────────

describe('M7.6 — renderPerformanceSummary — empty', () => {
  test('empty summary produces a printable shell with "no observations" line', () => {
    const text = renderPerformanceSummary(mkSummary(), {
      generated_at: NOW.toISOString(),
      generated_by: 'alice',
    });
    expect(text).toContain('MODEL PERFORMANCE — SUMMARY');
    expect(text).toContain('Tenant         : BIL');
    expect(text).toContain('Model ID       : pd_xgb_v3');
    expect(text).toContain('Generated at   : 2026-05-14T12:00:00.000Z');
    expect(text).toContain('Generated by   : alice');
    expect(text).toContain('Entry count    : 0');
    expect(text).toContain('(no observations on any metric in this window)');
    expect(text).toContain('END OF SUMMARY');
  });

  test('window line: when no range supplied → "full ledger" note', () => {
    const text = renderPerformanceSummary(mkSummary(), {
      generated_at: NOW.toISOString(),
      generated_by: 'alice',
    });
    expect(text).toContain('Window         : (full ledger — no since/until filter)');
  });

  test('window line: when range supplied → since → until format', () => {
    const text = renderPerformanceSummary(mkSummary(), {
      generated_at: NOW.toISOString(),
      generated_by: 'alice',
      range: { since: '2026-05-01T00:00:00Z', until: '2026-05-14T00:00:00Z' },
    });
    expect(text).toContain(
      'Window         : 2026-05-01T00:00:00Z → 2026-05-14T00:00:00Z',
    );
  });
});

describe('M7.6 — renderPerformanceSummary — populated', () => {
  test('present metric renders latest + mean + min/p50/p95/max line', () => {
    const text = renderPerformanceSummary(
      mkSummary({
        sample_size: 12,
        metrics: {
          precision: {
            latest_value: 0.85,
            latest_at: '2026-05-13T10:00:00.000Z',
            sample_count: 6,
            mean: 0.81,
            min: 0.7,
            p50: 0.82,
            p95: 0.9,
            max: 0.9,
          },
          recall: null,
          auc: null,
          drift_score: null,
          calibration_err: null,
        },
      }),
      { generated_at: NOW.toISOString(), generated_by: 'alice' },
    );
    expect(text).toContain('precision');
    expect(text).toContain('(n=6)');
    expect(text).toContain('latest          0.85  @ 2026-05-13T10:00:00.000Z');
    expect(text).toContain('mean            0.81');
    expect(text).toContain('min / p50 / p95 / max  0.7  /  0.82  /  0.9  /  0.9');
    // Absent metrics surface on the footer line.
    expect(text).toContain('Not observed: recall, auc, drift_score, calibration_err');
  });

  test('all 5 metrics present → no "Not observed" line', () => {
    const cell = (v: number) => ({
      latest_value: v,
      latest_at: '2026-05-13T10:00:00.000Z',
      sample_count: 3,
      mean: v,
      min: v,
      p50: v,
      p95: v,
      max: v,
    });
    const text = renderPerformanceSummary(
      mkSummary({
        sample_size: 15,
        metrics: {
          precision: cell(0.8),
          recall: cell(0.7),
          auc: cell(0.85),
          drift_score: cell(0.05),
          calibration_err: cell(0.03),
        },
      }),
      { generated_at: NOW.toISOString(), generated_by: 'alice' },
    );
    expect(text).not.toContain('Not observed:');
    // All 5 metric headers appear.
    for (const m of ['precision', 'recall', 'auc', 'drift_score', 'calibration_err']) {
      expect(text).toContain(m);
    }
  });

  test('numbers without decimals trim trailing zeros', () => {
    const text = renderPerformanceSummary(
      mkSummary({
        sample_size: 1,
        metrics: {
          precision: {
            latest_value: 1,
            latest_at: '2026-05-13T10:00:00.000Z',
            sample_count: 1,
            mean: 1,
            min: 1,
            p50: 1,
            p95: 1,
            max: 1,
          },
          recall: null,
          auc: null,
          drift_score: null,
          calibration_err: null,
        },
      }),
      { generated_at: NOW.toISOString(), generated_by: 'alice' },
    );
    expect(text).toContain('latest          1  @');
    expect(text).toContain('mean            1');
  });
});

// ─── GET /v1/ai/models/:model_id/performance/summary.txt ─────────────

function makeSummaryApp(role = 'admin') {
  const modelPerformanceStore = new InMemoryModelPerformanceStore(defaultAiModelRegistry);
  const built = makeApp({
    source: new StaticSource([]),
    evaluator: new StubEvaluator(),
    riskProfile: new StubRiskProfileSource(),
    caseAction: new UnavailableCaseActionSink(),
    modelPerformanceStore,
    now: () => NOW,
    getRole: () => role,
  });
  return { ...built, modelPerformanceStore };
}

describe('M7.6 — GET /v1/ai/models/:model_id/performance/summary.txt', () => {
  test('empty ledger → 200 text/plain with shell header', async () => {
    const { app } = makeSummaryApp('admin');
    const r = await request(app)
      .get('/v1/ai/models/pd_xgb_v3/performance/summary.txt')
      .set(TH_BIL)
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(200);
    expect(r.headers['content-type']).toContain('text/plain');
    expect(r.headers['content-disposition']).toContain('pd_xgb_v3');
    expect(r.text).toContain('MODEL PERFORMANCE — SUMMARY');
    expect(r.text).toContain('END OF SUMMARY');
  });

  test('after recording a metric, summary.txt surfaces it', async () => {
    const { app, modelPerformanceStore } = makeSummaryApp('admin');
    modelPerformanceStore.record(
      'BIL',
      'pd_xgb_v3',
      { metric: 'precision', value: 0.85, sample_size: 100 },
      NOW,
    );
    const r = await request(app)
      .get('/v1/ai/models/pd_xgb_v3/performance/summary.txt')
      .set(TH_BIL)
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(200);
    expect(r.text).toContain('precision');
    expect(r.text).toContain('(n=1)');
  });

  test('unknown model → 404 JSON (not text)', async () => {
    const { app } = makeSummaryApp('admin');
    const r = await request(app)
      .get('/v1/ai/models/no_such_model/performance/summary.txt')
      .set(TH_BIL)
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(404);
    expect(r.body.error.code).toBe('EWS_404_unknown_model');
  });

  test('?since/?until reflected in the Window header line', async () => {
    const { app } = makeSummaryApp('admin');
    const r = await request(app)
      .get('/v1/ai/models/pd_xgb_v3/performance/summary.txt?since=2026-05-01T00:00:00Z')
      .set(TH_BIL)
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(200);
    expect(r.text).toContain('Window         : 2026-05-01T00:00:00Z → —');
  });

  test('non-allowed role → 403', async () => {
    const { app } = makeSummaryApp('case_owner');
    const r = await request(app)
      .get('/v1/ai/models/pd_xgb_v3/performance/summary.txt')
      .set(TH_BIL)
      .set('x-apex-user', 'alice');
    expect(r.status).toBe(403);
  });

  test('M7.5 /summary still works (text route is additive)', async () => {
    const { app } = makeSummaryApp('admin');
    const r = await request(app)
      .get('/v1/ai/models/pd_xgb_v3/performance/summary')
      .set(TH_BIL);
    expect(r.status).toBe(200);
    // JSON envelope, not text/plain
    expect(r.headers['content-type']).toContain('application/json');
  });
});
